#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd ../../cutHexMesh

if(wmake)
then
    cd -

    runApplication blockMesh
    cutHexMesh plane1.stl
fi
    
    
# ----------------------------------------------------------------- end-of-file
