#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd ../../cutHexMesh


if(wmake)
then
    cd -

    blockMesh > /dev/null
    moveMeshPoints $1 $2 -overwrite
    cutHexMesh $1
fi
    
    
# ----------------------------------------------------------------- end-of-file
