#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd ../../surfaceOffset


if(wmake)
then
    cd -

    surfaceOffset $1 $2 out.stl
fi
    
    
# ----------------------------------------------------------------- end-of-file
